In [3]:
import numpy as np # linear algebra

# Introducción a Numpy

Numpy es una libreria de codigo abierto que se usa en casi todos los campos de la ciencia y la ingenieria. Es una libreria que se usa como base, en otras como por ejemplo Pandas, SciPy, Matplotlib, scikit-learn, scikit-image, etc.

Introduce entre otras cosas el array n-dimensional, con metodos optimizados para trabajar con estos, y es garantia de calculo eficiente proporcinando un gran numero de funciones de alto nivel para operar con arrays y matrices.

### Guia de Introducción a Numpy
https://numpy.org/doc/stable/user/absolute_beginners.html
#### Guias de Numpy para ciencia de datos
https://colab.research.google.com/github/futurelabmx/cdecmx/blob/main/B%20-%20Intro%20a%20NumPy.ipynb

https://rafneta.github.io/CienciaDatosPythonCIDE/Laboratorios/Lab8/numpy.html

# Inicializar vectores y matrices a partir de listas

In [4]:
a = np.array([1,2,3,4,5,6])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a.shape

(6,)

In [8]:
a.size

6

In [9]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(type(b))

<class 'numpy.ndarray'>


In [11]:
b.ndim

2

In [12]:
b.shape

(3, 4)

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
x = np.linspace(0,9,10)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
y = np.arange(0,10,1)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
type(y[0])

numpy.int32

# Broadcasting

In [21]:
ones = np.ones(11)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
ones + 2

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [23]:
ones * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [24]:
ones / 2

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [25]:
b+1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

# Traspuesta y aplanado

In [26]:
b.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [27]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
b.flatten().ndim

1

# Vectorizacion de loops
## Multiplicacion elemento a elemento

In [29]:
v = np.array([1,2,3],dtype=float)
w = np.array([2,4,8],dtype=float)
u = np.zeros(3)

In [30]:
for i in range(3):
    u[i] = 2 * v[i] + w[i]
u

array([ 4.,  8., 14.])

Pero podemos hacer elemento a elemento implicito:

In [31]:
u = 2*v + w
u

array([ 4.,  8., 14.])

In [32]:
m = np.array(np.mat('1 2 3; 4 5 6;7 8 9'),dtype=float)
w = np.array([2,4,8],dtype=float)
r = np.zeros(3)

In [61]:
# si no se cumple, imprime el mensaje
assert w.size == m.shape[1], "Tamaños que no coinciden (n,k),(k,m)->(n,m)" 

In [62]:
#dot, producto escalar o producto punto entre vector y matriz
for i in range (m.shape[0]):
    r[i]=0
    for j in range(w.size):
        r[i] += w[j]*m[i,j]
r        

array([ 34,  76, 118])

Otra forma es con np.matmul() o np.dot(). Ver el help, es algo sobre como toma los datos, si los guarda en stack o no.

In [35]:
r = np.matmul(m,w)
r

array([ 34.,  76., 118.])

In [36]:
r = np.dot(m,w)
r

array([ 34.,  76., 118.])

In [37]:
#help(np.matmul)

In [38]:
# Producto vectorial
r = np.cross([1,0,0],[0,1,0])
r

array([0, 0, 1])

# Funcion basicas

In [39]:
print(m.max())

9.0


In [63]:
m

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [40]:
print(m.max(axis=0))

[7. 8. 9.]


In [41]:
print(m.max(axis=1))

[3. 6. 9.]


In [42]:
m.mean()

5.0

In [43]:
m.std()

2.581988897471611

In [44]:
np.sin(m/10)

array([[0.09983342, 0.19866933, 0.29552021],
       [0.38941834, 0.47942554, 0.56464247],
       [0.64421769, 0.71735609, 0.78332691]])

In [45]:
np.unique(np.identity(100))

array([0., 1.])

# Slicing

In [64]:
r = np.array([0,1,2])

In [47]:
r[1]

1

In [48]:
r[-1]

2

In [70]:
# elejimos la posiciones que queremos
r[np.array([0,2])]


array([0, 2])

In [50]:
m

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [71]:
# todos los elementos de la primer dimension, y solo el elemento 0 de la segunda
m[:,0]

array([1., 4., 7.])

In [52]:
m[:,1]

array([2., 5., 8.])

In [81]:
# 0 al 2 sin incluir de la primer dimension, y le 0 de la segunda dimension
m[0:2,0]

array([1., 4.])

In [54]:
m[0:2,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [83]:
m[0:-1,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
m[1:,:]

array([[4., 5., 6.],
       [7., 8., 9.]])

# Codificacion one hot  
Se llama asi porque tiene un 1 y el resto en 0

In [57]:
nb_classes = 10
print(np.identity(nb_classes))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [58]:
targets = np.array([2,3,4,0,8])
targets

array([2, 3, 4, 0, 8])

In [59]:
np.nan

nan

In [60]:
# se puede hacer con multiplicacion de matriz con vector
# o se pueda hace con slicing, instancio la matriz y me quedo con los elementos (filas) deseadas
one_hot = np.identity(nb_classes)[targets]
one_hot

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])